/** Editable CAD-as-code. Geometry is generated by the upstream build123d API. */
export interface CadProgram {
	version: 1;
	engine: "build123d";
	name: string;
	units: "mm" | "in";
	parameters: Record<string, number>;
	source: string;
	/** Immutable input snapshot key -> live editor node id. */
	imports: Record<string, string>;
	removedParts: string[];
	assumptions: string[];
}

export interface CadSource {
	nodeId: string;
	brep: string;
}
export interface CadPart {
	id: string;
	name: string;
	nodeId?: string;
	material?: string;
	brep: string;
	fingerprint: string;
	volumeMm3: number;
	minMm: number[];
	maxMm: number[];
	sizeMm: number[];
}
export interface CadBuild {
	program: CadProgram;
	parts: CadPart[];
	sources: Record<string, CadSource>;
	libraryVersion: string;
	kernelVersion: string;
}
export interface CadLiveUpdate {
	activity: string[];
	text: string;
	draftCharacters: number;
	previewRevision: number;
	previewCount: number;
	/** Absent when unchanged, null when the previous draft must be cleared. */
	preview?: CadPart[] | null;
}

const idPattern = /^[a-zA-Z0-9][a-zA-Z0-9_-]{0,119}$/;
export function validateCadProgram(
	value: unknown,
): asserts value is CadProgram {
	const p = value as CadProgram | null;
	if (
		!p ||
		p.version !== 1 ||
		p.engine !== "build123d" ||
		!["mm", "in"].includes(p.units)
	)
		throw new Error("Invalid build123d program header");
	if (typeof p.name !== "string" || !p.name.trim() || p.name.length > 200)
		throw new Error("Invalid model name");
	if (
		typeof p.source !== "string" ||
		!p.source.trim() ||
		p.source.length > 150000
	)
		throw new Error("CAD source must contain 1–150,000 characters");
	if (
		!p.parameters ||
		Array.isArray(p.parameters) ||
		typeof p.parameters !== "object" ||
		Object.keys(p.parameters).length > 100
	)
		throw new Error("Invalid CAD parameters");
	for (const [key, number] of Object.entries(p.parameters)) {
		if (
			!idPattern.test(key) ||
			!Number.isFinite(number) ||
			Math.abs(number) > 1e9
		)
			throw new Error(`Invalid CAD parameter ${key}`);
	}
	if (
		!p.imports ||
		Array.isArray(p.imports) ||
		typeof p.imports !== "object" ||
		Object.keys(p.imports).length > 1000
	)
		throw new Error("Invalid CAD imports");
	for (const [key, nodeId] of Object.entries(p.imports)) {
		if (
			!idPattern.test(key) ||
			typeof nodeId !== "string" ||
			!nodeId ||
			nodeId.length > 160
		)
			throw new Error("Invalid CAD input snapshot");
	}
	if (
		!Array.isArray(p.removedParts) ||
		p.removedParts.length > 1000 ||
		p.removedParts.some((id) => typeof id !== "string" || !idPattern.test(id))
	)
		throw new Error("Invalid removed parts");
	if (
		!Array.isArray(p.assumptions) ||
		p.assumptions.length > 40 ||
		p.assumptions.some((a) => typeof a !== "string" || a.length > 1000)
	)
		throw new Error("Invalid model assumptions");
}

export function cadNodeId(part: Pick<CadPart, "id" | "nodeId">): string {
	return part.nodeId ?? `cad-${part.id}`;
}

export function validateCadBuild(value: unknown): asserts value is CadBuild {
	const build = value as CadBuild;
	if (!build || typeof build !== "object") throw new Error("Invalid CAD build");
	validateCadProgram(build.program);
	validateCadParts(build.parts);
	if (
		!build.sources ||
		typeof build.sources !== "object" ||
		Array.isArray(build.sources)
	)
		throw new Error("Invalid CAD source snapshots");
	for (const [key, nodeId] of Object.entries(build.program.imports)) {
		const source = build.sources[key];
		if (
			!source ||
			source.nodeId !== nodeId ||
			typeof source.brep !== "string" ||
			!source.brep.includes("CASCADE Topology")
		)
			throw new Error(`Missing immutable input ${key}`);
	}
}

export function validateCadParts(value: unknown): asserts value is CadPart[] {
	const parts = value as CadPart[];
	if (!Array.isArray(parts) || !parts.length || parts.length > 1000)
		throw new Error("A model requires 1–1,000 named parts");
	const ids = new Set<string>();
	const targets = new Set<string>();
	let bytes = 0;
	for (const p of parts) {
		if (
			!idPattern.test(p.id) ||
			ids.has(p.id) ||
			typeof p.name !== "string" ||
			!p.name ||
			p.name.length > 200
		)
			throw new Error("Invalid or duplicate CAD part");
		if (
			p.nodeId !== undefined &&
			(typeof p.nodeId !== "string" || !p.nodeId || p.nodeId.length > 160)
		)
			throw new Error("Invalid target node");
		if (targets.has(cadNodeId(p)))
			throw new Error("Two CAD parts cannot replace the same node");
		ids.add(p.id);
		targets.add(cadNodeId(p));
		if (
			typeof p.brep !== "string" ||
			p.brep.length < 30 ||
			!p.brep.includes("CASCADE Topology") ||
			typeof p.fingerprint !== "string" ||
			!/^[a-f0-9]{64}$/.test(p.fingerprint)
		)
			throw new Error("Invalid CAD geometry");
		bytes += p.brep.length;
		if (!Number.isFinite(p.volumeMm3) || p.volumeMm3 <= 1e-9)
			throw new Error(`${p.name}: part must have positive solid volume`);
		for (const vector of [p.minMm, p.maxMm, p.sizeMm])
			if (
				!Array.isArray(vector) ||
				vector.length !== 3 ||
				vector.some((v) => !Number.isFinite(v) || Math.abs(v) > 1e7)
			)
				throw new Error("Invalid model bounds");
		if (
			p.material !== undefined &&
			(typeof p.material !== "string" || p.material.length > 200)
		)
			throw new Error("Invalid material");
	}
	if (bytes > 32 * 1024 * 1024)
		throw new Error(
			"Generated geometry exceeds 32 MB; split the model into subassemblies",
		);
}
