import type {
  EstimateFactor,
  EstimateFactorApplicationScope,
  EstimateFactorConfidence,
  EstimateFactorFormulaType,
  EstimateFactorImpact,
  EstimateFactorScope,
  EstimateFactorSourceType,
} from "./models";

export interface EstimateFactorPreset {
  id: string;
  name: string;
  code: string;
  description: string;
  category: string;
  impact: EstimateFactorImpact;
  value: number;
  appliesTo: string;
  applicationScope?: EstimateFactorApplicationScope;
  scope: EstimateFactorScope;
  formulaType?: EstimateFactorFormulaType;
  parameters?: Record<string, unknown>;
  confidence: EstimateFactorConfidence;
  sourceType: EstimateFactorSourceType;
  sourceId?: string | null;
  sourceRef: Record<string, unknown>;
  tags: string[];
}

function bookSourceRef(input: {
  bookId: string;
  title: string;
  fileName: string;
  locator: string;
  basis: string;
  formula?: string;
}) {
  return {
    bookId: input.bookId,
    title: input.title,
    fileName: input.fileName,
    locator: input.locator,
    basis: input.basis,
    formula: input.formula,
    verification: "Extracted from local knowledge-book text/tables; verify project applicability before final issue.",
  };
}

const pipingBook = {
  bookId: "kb-f121e3f3-3710-490f-baa9-f3d46f4c54eb",
  title: "Estimator's Piping Man-Hour Manual",
  fileName: "Estimators-Piping-Man-Hour.pdf",
};

const equipmentBook = {
  bookId: "kb-ab080d32-f633-4654-a4da-cc8ea72be57b",
  title: "Estimator's Equipment Installation Man-Hour Manual",
  fileName: "Estimators_Equipment_Installation_Man-Hour_Manual_John_S._Page_z-lib.org_.pdf",
};

const electricalBook = {
  bookId: "kb-5dc816f5-b5c9-41a3-acd0-ae83b1fcf438",
  title: "Electrical Estimator's Manual",
  fileName: "178752378-Electrical-Estimator-s-Manual-pdf.pdf",
};

export const LABOR_CONDITION_CRITERIA = [
  { condition: "Working conditions", considerations: "Indoor, controlled environment, extreme conditions" },
  { condition: "Working height", considerations: "Up to 10 ft, 10-20 ft, 20 ft plus; ladders/lifts/scaffold; below grade" },
  { condition: "Building height", considerations: "Number of floors: 1-3, 4-7, high-rise" },
  { condition: "Building sq. ft.", considerations: "Manageable, moderate, excessive" },
  { condition: "Project size in dollars", considerations: "Normal, moderate, extreme" },
  { condition: "Site size", considerations: "Urban setting, ample laydown space" },
  { condition: "Job conditions", considerations: "New construction, remodel, work while occupied" },
  { condition: "Type of construction", considerations: "Frame, block, concrete or exposed" },
  { condition: "Hours worked", considerations: "40 hours/week; 5, 6, or 7 day work week; 8, 10, or 12 hour work day" },
  { condition: "Shifts", considerations: "Day, 2nd, 3rd" },
  { condition: "Crew density", considerations: "Normal, moderate, extreme" },
  { condition: "Project duration", considerations: "Normal, compressed, delayed, fast track" },
  { condition: "Safety", considerations: "Standard OSHA guidelines, customer directives, project specific" },
  { condition: "Installation", considerations: "Repetitive, moderately repetitive, no repetition" },
  { condition: "Systems", considerations: "Common systems, special, complex" },
  { condition: "Conduit type", considerations: "PVC, EMT, flex or GRC, IMC, aluminum, PVC coated GRC" },
  { condition: "Accessibility of work area", considerations: "Unlimited, limited, escorted" },
  { condition: "Voltage", considerations: "0-600V, 600-5kV, over 5kV" },
  { condition: "Inventory of local supplier", considerations: "Adequate, moderate, limited" },
  { condition: "Proximity of stored materials", considerations: "On site, in general area of project, remote" },
  { condition: "Project continuity", considerations: "Interruptions: none, moderate, extreme" },
  { condition: "Construction", considerations: "Standard, poor, none" },
  { condition: "Drawings/plans", considerations: "Percent complete: 100%, 95%, 50%, 35%, less" },
  { condition: "Information", considerations: "Timely, delayed, limited" },
  { condition: "Change order quantity/timing", considerations: "Minimal, moderate, excessive; prior to installation, during, after" },
  { condition: "Craft coordination required", considerations: "Minimum, moderate, extensive" },
  { condition: "Authority having jurisdiction", considerations: "Experience with type of project: considerable, moderate, limited" },
  { condition: "Decision making", considerations: "Timely, delayed, limited" },
  { condition: "BIM Building Integrated Modeling", considerations: "General/owner uses BIM proactively, moderately proactive, only to satisfy contract condition" },
  { condition: "Project schedule", considerations: "As planned, compressed/extended, moderate, extreme" },
  { condition: "General contractors on same jobsite", considerations: "Single prime, two primes, three plus primes" },
  { condition: "Job meetings", considerations: "Regularly scheduled, crisis meetings, minimal" },
  { condition: "Shared responsibility for project", considerations: "One EC, two ECs, three plus ECs on site" },
  { condition: "Tools/equipment", considerations: "Standard, non-standard, specialty" },
  { condition: "Labor availability", considerations: "Readily available, moderately available, limited, non-available" },
];

export const NECA_JOB_CONDITION_CRITERIA = LABOR_CONDITION_CRITERIA;

export const NECA_TEMPERATURE_PRODUCTIVITY_SAMPLES = [
  { temperatureF: 40, humidity: 30, productivity: 100 },
  { temperatureF: 35, humidity: 30, productivity: 100 },
  { temperatureF: 34, humidity: 30, productivity: 98 },
  { temperatureF: 24, humidity: 30, productivity: 94 },
  { temperatureF: 14, humidity: 30, productivity: 88 },
  { temperatureF: 4, humidity: 30, productivity: 78 },
  { temperatureF: -5, humidity: 30, productivity: 62 },
  { temperatureF: -15, humidity: 30, productivity: 62 },
  { temperatureF: -15, humidity: 44, productivity: 62 },
  { temperatureF: -15, humidity: 45, productivity: 61 },
  { temperatureF: -15, humidity: 55, productivity: 60 },
  { temperatureF: -15, humidity: 65, productivity: 59 },
  { temperatureF: -15, humidity: 75, productivity: 57 },
  { temperatureF: -15, humidity: 85, productivity: 55 },
  { temperatureF: -15, humidity: 90, productivity: 55 },
  { temperatureF: -4, humidity: 90, productivity: 71 },
  { temperatureF: 5, humidity: 90, productivity: 82 },
  { temperatureF: 15, humidity: 90, productivity: 89 },
  { temperatureF: 25, humidity: 90, productivity: 93 },
  { temperatureF: 35, humidity: 90, productivity: 96 },
  { temperatureF: 45, humidity: 90, productivity: 98 },
  { temperatureF: 65, humidity: 90, productivity: 96 },
  { temperatureF: 75, humidity: 90, productivity: 93 },
  { temperatureF: 85, humidity: 90, productivity: 84 },
  { temperatureF: 95, humidity: 90, productivity: 57 },
];

export const NECA_EXTENDED_DURATION_TABLE = [
  { laborHours: 500, laborDays: 62, workers: 2, crewWeeks: 6, normalMonths: 2, factor: 8, extraHours: 40 },
  { laborHours: 1000, laborDays: 125, workers: 3, crewWeeks: 8, normalMonths: 3, factor: 6.5, extraHours: 65 },
  { laborHours: 1250, laborDays: 156, workers: 4, crewWeeks: 8, normalMonths: 3, factor: 6.5, extraHours: 81 },
  { laborHours: 2500, laborDays: 313, workers: 5, crewWeeks: 10, normalMonths: 4, factor: 5, extraHours: 125 },
  { laborHours: 5000, laborDays: 625, workers: 8, crewWeeks: 16, normalMonths: 5, factor: 4, extraHours: 200 },
  { laborHours: 10000, laborDays: 1250, workers: 11, crewWeeks: 23, normalMonths: 7, factor: 3.5, extraHours: 350 },
  { laborHours: 15000, laborDays: 1875, workers: 14, crewWeeks: 27, normalMonths: 8, factor: 2.75, extraHours: 415 },
  { laborHours: 20000, laborDays: 2500, workers: 15, crewWeeks: 34, normalMonths: 10, factor: 2.25, extraHours: 450 },
  { laborHours: 30000, laborDays: 3750, workers: 17, crewWeeks: 44, normalMonths: 12, factor: 1.75, extraHours: 525 },
  { laborHours: 45000, laborDays: 5625, workers: 25, crewWeeks: 45, normalMonths: 12, factor: 1.75, extraHours: 785 },
  { laborHours: 60000, laborDays: 7500, workers: 30, crewWeeks: 50, normalMonths: 14, factor: 1.45, extraHours: 870 },
  { laborHours: 75000, laborDays: 9400, workers: 35, crewWeeks: 54, normalMonths: 15, factor: 1.35, extraHours: 1010 },
  { laborHours: 100000, laborDays: 12500, workers: 38, crewWeeks: 65, normalMonths: 18, factor: 1.25, extraHours: 1250 },
  { laborHours: 125000, laborDays: 15650, workers: 40, crewWeeks: 78, normalMonths: 21, factor: 1.15, extraHours: 1445 },
  { laborHours: 150000, laborDays: 18750, workers: 45, crewWeeks: 83, normalMonths: 22, factor: 1, extraHours: 1500 },
  { laborHours: 200000, laborDays: 25000, workers: 58, crewWeeks: 86, normalMonths: 23, factor: 0.95, extraHours: 1900 },
  { laborHours: 250000, laborDays: 33000, workers: 70, crewWeeks: 90, normalMonths: 24, factor: 0.85, extraHours: 2120 },
  { laborHours: 300000, laborDays: 37500, workers: 80, crewWeeks: 94, normalMonths: 26, factor: 0.84, extraHours: 2520 },
];

export const NECA_DIFFICULTY_RANGES = [
  { label: "Normal", minScore: 0, maxScore: 75, multiplier: 1 },
  { label: "Difficult", minScore: 76, maxScore: 134, multiplier: 1.15 },
  { label: "Very Difficult", minScore: 135, maxScore: 180, multiplier: 1.3 },
];

function laborConditionSourceRef(input: { locator: string; basis: string; formula: string; difficultyBand?: string }) {
  return {
    title: "Labor Condition Score Sheet",
    fileName: "../adminapp2-main/resources/views/quotes/tools/toolNECAJobCondition.blade.php",
    pluginSlug: "toolNECAJobCondition",
    locator: input.locator,
    basis: input.basis,
    formula: input.formula,
    difficultyBand: input.difficultyBand,
    scoreSheet: {
      criteria: LABOR_CONDITION_CRITERIA,
      scoreScale: "Each criterion scores 0-5.",
      ranges: [
        { label: "Normal", minScore: 0, maxScore: 75, multiplier: 1 },
        { label: "Difficult", minScore: 76, maxScore: 134, multiplier: 1.15 },
        { label: "Very Difficult", minScore: 135, maxScore: 180, multiplier: 1.3 },
      ],
    },
    verification: "Lifted from the legacy adminapp2 job-condition tool and aligned with the local labor-units difficulty multipliers.",
  };
}

function slugifyFactorId(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

const LABOR_CONDITION_FACTOR_PRESETS: EstimateFactorPreset[] = LABOR_CONDITION_CRITERIA.map((criterion, index) => ({
  id: `labor-condition-${String(index + 1).padStart(2, "0")}-${slugifyFactorId(criterion.condition)}`,
  name: criterion.condition,
  code: `COND-${String(index + 1).padStart(2, "0")}`,
  category: "Labor Conditions",
  description: `Score this condition from 0-5. Considerations: ${criterion.considerations}. The calibration uses the researched 35-condition labor factor score sheet rather than a pre-rolled difficulty preset.`,
  impact: "labor_hours",
  value: 1,
  appliesTo: "Electrical labor",
  applicationScope: "global",
  scope: { mode: "category", analyticsBuckets: ["labour", "labor"], categoryNames: ["Electrical", "Labour", "Labor"] },
  formulaType: "condition_score",
  parameters: {
    condition: criterion.condition,
    considerations: criterion.considerations,
    score: 0,
    maxScore: 5,
    calibrationTotalScore: 175,
    calibrationMultiplier: 1.3,
    scoreSheetRow: index + 1,
    scoreScale: "0 = not applicable or normal; 5 = severe productivity constraint.",
  },
  confidence: "medium",
  sourceType: "condition_difficulty",
  sourceId: "labor-condition-score-sheet",
  sourceRef: laborConditionSourceRef({
    locator: `Labor condition row ${index + 1}: ${criterion.condition}`,
    basis: `Condition and considerations sourced from the 35-row labor factor score sheet: ${criterion.considerations}.`,
    formula: "Individual factor multiplier = 1.30 ^ (score / 175), so all 35 rows scored at 5 calibrate to a combined 1.30x labor-hour factor.",
    difficultyBand: "Split into individual condition factors from the score sheet.",
  }),
  tags: ["electrical", "labor", "difficulty", "job-conditions", "score-sheet", slugifyFactorId(criterion.condition)],
}));

export const ESTIMATE_FACTOR_PRESETS: EstimateFactorPreset[] = [
  {
    id: "page-composite-productivity-65",
    name: "Composite Productivity 65%",
    code: "PAGE-PROD-65",
    category: "Composite Productivity",
    description: "Use when the project productivity review evaluates to 65% against Page's 70% baseline, producing a five-percent labor adjustment.",
    impact: "labor_hours",
    value: 1.05,
    appliesTo: "Labour",
    scope: { mode: "category", analyticsBuckets: ["labour", "labor"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: pipingBook.bookId,
    sourceRef: bookSourceRef({
      ...pipingBook,
      locator: "Production and Composite Rate",
      basis: "Manual bases man-hours on 70% productivity and gives a 65% evaluated productivity example with a 5% adjustment.",
      formula: "65% evaluated productivity vs 70% manual basis => +5%",
    }),
    tags: ["page", "productivity", "composite", "weather", "job-conditions"],
  },
  {
    id: "piping-sloping-lines-welding",
    name: "Sloping Line Welding",
    code: "PIPE-WELD-SLOPING",
    category: "Piping Welding",
    description: "Apply to welding hours for sloping piping where the Page piping manual requires doubling welding man-hours.",
    impact: "labor_hours",
    value: 2,
    appliesTo: "Piping weld labor",
    scope: { mode: "text", text: ["weld", "sloping"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: pipingBook.bookId,
    sourceRef: bookSourceRef({
      ...pipingBook,
      locator: "Nozzle Welds / Sloping Lines notes",
      basis: "Manual states sloping lines add 100% to welding man-hours.",
      formula: "+100% welding man-hours",
    }),
    tags: ["piping", "welding", "sloping-lines"],
  },
  {
    id: "piping-nozzle-off-center",
    name: "Off-Center Nozzle Weld",
    code: "PIPE-NOZZLE-OFFCENTER",
    category: "Piping Welding",
    description: "Apply to nozzle welds located off-center of the run, excluding tangential nozzles.",
    impact: "labor_hours",
    value: 1.5,
    appliesTo: "Nozzle weld labor",
    scope: { mode: "text", text: ["nozzle", "weld", "off-center"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: pipingBook.bookId,
    sourceRef: bookSourceRef({
      ...pipingBook,
      locator: "Nozzle Welds notes",
      basis: "Manual allows a 50% increase for off-center nozzle welds.",
      formula: "+50% nozzle weld man-hours",
    }),
    tags: ["piping", "welding", "nozzles"],
  },
  {
    id: "piping-nozzle-tangential",
    name: "Tangential Nozzle Weld",
    code: "PIPE-NOZZLE-TANGENTIAL",
    category: "Piping Welding",
    description: "Apply to tangential nozzle welds where Page identifies additional fit-up and welding effort.",
    impact: "labor_hours",
    value: 1.8,
    appliesTo: "Tangential nozzle weld labor",
    scope: { mode: "text", text: ["nozzle", "tangential"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: pipingBook.bookId,
    sourceRef: bookSourceRef({
      ...pipingBook,
      locator: "Nozzle Welds notes",
      basis: "Manual allows an 80% increase for tangential nozzle welds.",
      formula: "+80% nozzle weld man-hours",
    }),
    tags: ["piping", "welding", "nozzles"],
  },
  {
    id: "piping-flanged-20ft-factory",
    name: "20 ft Factory-Flanged Pipe Handling",
    code: "PIPE-FLANGED-20FT",
    category: "Piping Handling",
    description: "Apply to handling hours where pipe is received from the factory in flanged 20-foot lengths.",
    impact: "labor_hours",
    value: 1.1,
    appliesTo: "Pipe handling labor",
    scope: { mode: "text", text: ["pipe", "flanged", "20 foot"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: pipingBook.bookId,
    sourceRef: bookSourceRef({
      ...pipingBook,
      locator: "Field fabrication pipe-unit notes",
      basis: "Manual adds 10% to pipe handling man-hours for factory flanged 20-foot lengths.",
      formula: "+10% pipe handling man-hours",
    }),
    tags: ["piping", "handling", "flanged"],
  },
  {
    id: "piping-factory-flanged-extra-weight",
    name: "Factory-Flanged Pipe Extra Weight",
    code: "PIPE-FLANGED-WEIGHT",
    category: "Piping Handling",
    description: "Apply when factory-furnished pipe includes threaded ends and flanges that increase handling weight.",
    impact: "labor_hours",
    value: 1.15,
    appliesTo: "Pipe handling labor",
    scope: { mode: "text", text: ["pipe", "factory", "flange"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: pipingBook.bookId,
    sourceRef: bookSourceRef({
      ...pipingBook,
      locator: "Field fabrication pipe-unit notes",
      basis: "Manual adds 15% to pipe man-hours for handling additional factory-flanged weight.",
      formula: "+15% pipe man-hours",
    }),
    tags: ["piping", "handling", "factory-flanged"],
  },
  {
    id: "piping-segmented-pressure-test",
    name: "Segmented Pressure Testing",
    code: "PIPE-TEST-SEGMENTED",
    category: "Testing",
    description: "Apply to pressure-test labor when individual pipe segments or spools must be tested separately.",
    impact: "labor_hours",
    value: 10,
    appliesTo: "Pressure test labor",
    scope: { mode: "text", text: ["test", "spool", "segment"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: pipingBook.bookId,
    sourceRef: bookSourceRef({
      ...pipingBook,
      locator: "Pressure testing notes",
      basis: "Manual says separate segment/spool testing multiplies listed man-hours by ten.",
      formula: "x10 pressure-test man-hours",
    }),
    tags: ["piping", "testing", "spools"],
  },
  {
    id: "equipment-height-30ft",
    name: "Equipment Set Above 20 ft",
    code: "EQUIP-HEIGHT-30FT",
    category: "Equipment Elevation",
    description: "Example preset for equipment set 10 feet above the 20-foot basis; adjust percent for actual elevation.",
    impact: "labor_hours",
    value: 1.025,
    appliesTo: "Equipment setting labor",
    scope: { mode: "text", text: ["equipment", "fan", "air-conditioning", "height"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: equipmentBook.bookId,
    sourceRef: bookSourceRef({
      ...equipmentBook,
      locator: "Air-conditioning units and fan notes",
      basis: "Manual increases man-hours one-quarter percent for each foot above 20 feet.",
      formula: "+0.25% per foot above 20 ft; preset assumes 30 ft",
    }),
    tags: ["equipment", "height", "elevation"],
  },
  {
    id: "equipment-congested-area-review",
    name: "Congested Equipment Erection Review",
    code: "EQUIP-CONGESTED-REVIEW",
    category: "Equipment Access",
    description: "Manual requires separate evaluation where vessel erection occurs in a congested area; default is neutral until evidence sets the multiplier.",
    impact: "labor_hours",
    value: 1,
    appliesTo: "Equipment erection labor",
    scope: { mode: "text", text: ["vessel", "erect", "congested"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: equipmentBook.bookId,
    sourceRef: bookSourceRef({
      ...equipmentBook,
      locator: "Vessel erection notes",
      basis: "Manual states congested vessel erection should be evaluated separately and adjusted.",
    }),
    tags: ["equipment", "congestion", "review-required"],
  },
  {
    id: "electrical-explosion-proof",
    name: "Explosion-Proof Electrical Labor",
    code: "ELEC-EXPLOSION-PROOF",
    category: "Electrical Installation",
    description: "Apply to applicable electrical labor where explosion-proof devices or installations are required.",
    impact: "labor_hours",
    value: 2,
    appliesTo: "Electrical labor",
    scope: { mode: "text", text: ["explosion proof", "hazardous"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: electricalBook.bookId,
    sourceRef: bookSourceRef({
      ...electricalBook,
      locator: "Electrical estimating labor notes",
      basis: "Manual adds 100% to labor for explosion-proof work.",
      formula: "+100% labor",
    }),
    tags: ["electrical", "explosion-proof", "hazardous"],
  },
  {
    id: "electrical-pvc-coated-rgc",
    name: "PVC-Coated Exposed RGC",
    code: "ELEC-PVC-RGC",
    category: "Electrical Raceway",
    description: "Apply to exposed rigid galvanized conduit labor when PVC-coated conduit is used.",
    impact: "labor_hours",
    value: 1.25,
    appliesTo: "Raceway labor",
    scope: { mode: "text", text: ["PVC-coated", "RGC", "conduit"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: electricalBook.bookId,
    sourceRef: bookSourceRef({
      ...electricalBook,
      locator: "Raceway labor notes",
      basis: "Manual adds 25% to exposed RGC hours for PVC-coated conduit.",
      formula: "+25% exposed RGC hours",
    }),
    tags: ["electrical", "raceway", "PVC-coated"],
  },
  {
    id: "electrical-aluminum-raceway",
    name: "Aluminum Raceway Deduct",
    code: "ELEC-AL-RACEWAY",
    category: "Electrical Raceway",
    description: "Apply when aluminum raceways and fittings replace the standard raceway basis.",
    impact: "labor_hours",
    value: 0.85,
    appliesTo: "Raceway labor",
    scope: { mode: "text", text: ["aluminum", "raceway", "fittings"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: electricalBook.bookId,
    sourceRef: bookSourceRef({
      ...electricalBook,
      locator: "Raceway labor notes",
      basis: "Manual deducts 15% when installing aluminum raceways and fittings.",
      formula: "-15% labor",
    }),
    tags: ["electrical", "raceway", "aluminum", "efficiency"],
  },
  {
    id: "electrical-fixture-height-plus-5ft",
    name: "Fixture Height Above 12 ft",
    code: "ELEC-FIXTURE-HEIGHT",
    category: "Electrical Lighting",
    description: "Apply per five-foot increase above the 12-foot ceiling-height labor basis.",
    impact: "labor_hours",
    value: 1.25,
    appliesTo: "Fixture labor",
    scope: { mode: "text", text: ["fixture", "ceiling height"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: electricalBook.bookId,
    sourceRef: bookSourceRef({
      ...electricalBook,
      locator: "Lighting fixture labor notes",
      basis: "Manual bases labor on 12 feet or less and adds 25% for each 5-foot increase.",
      formula: "+25% per 5 ft above 12 ft",
    }),
    tags: ["electrical", "lighting", "height"],
  },
  {
    id: "electrical-weatherproof-installation",
    name: "Weatherproof Electrical Installation",
    code: "ELEC-WEATHERPROOF",
    category: "Electrical Installation",
    description: "Apply to electrical items where weatherproof installation is required by plans or specifications.",
    impact: "labor_hours",
    value: 1.2,
    appliesTo: "Electrical labor",
    scope: { mode: "text", text: ["weatherproof"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: electricalBook.bookId,
    sourceRef: bookSourceRef({
      ...electricalBook,
      locator: "Electrical labor notes",
      basis: "Manual adds 20% for weatherproof installation where required.",
      formula: "+20% labor",
    }),
    tags: ["electrical", "weatherproof", "outdoor"],
  },
  {
    id: "electrical-install-above-15-to-25",
    name: "Electrical Install Above 15 ft",
    code: "ELEC-HEIGHT-15-25",
    category: "Electrical Installation",
    description: "Apply to applicable electrical labor for installation above 15 feet up to 25 feet.",
    impact: "labor_hours",
    value: 1.35,
    appliesTo: "Electrical labor",
    scope: { mode: "text", text: ["install above", "15", "25"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: electricalBook.bookId,
    sourceRef: bookSourceRef({
      ...electricalBook,
      locator: "Electrical labor notes",
      basis: "Manual adds 35% to labor hours to install above 15 feet up to 25 feet.",
      formula: "+35% labor",
    }),
    tags: ["electrical", "height", "access"],
  },
  {
    id: "electrical-demolition-rule",
    name: "Electrical Demolition Rule",
    code: "ELEC-DEMO-50",
    category: "Electrical Demolition",
    description: "Use when electrical demolition labor should be estimated from installation labor.",
    impact: "labor_hours",
    value: 0.5,
    appliesTo: "Electrical demolition labor",
    scope: { mode: "text", text: ["demolition", "remove", "demo"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: electricalBook.bookId,
    sourceRef: bookSourceRef({
      ...electricalBook,
      locator: "Miscellaneous information",
      basis: "Manual states electrical demolition labor is one-half of installation labor.",
      formula: "50% of installation labor",
    }),
    tags: ["electrical", "demolition", "rule-of-thumb"],
  },
  {
    id: "electrical-tool-factor",
    name: "Electrical Tool Factor",
    code: "ELEC-TOOL-FACTOR",
    category: "Electrical Job Expense",
    description: "Apply to material-cost scope when recapitulation calls for a tool factor at one percent of materials.",
    impact: "direct_cost",
    value: 1.01,
    appliesTo: "Materials",
    scope: { mode: "category", analyticsBuckets: ["material", "materials"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: electricalBook.bookId,
    sourceRef: bookSourceRef({
      ...electricalBook,
      locator: "Recapitulation sheet",
      basis: "Manual recapitulation includes tool factor as 1% of materials.",
      formula: "+1% of material line cost",
    }),
    tags: ["electrical", "tools", "job-expense"],
  },
  {
    id: "electrical-cleanup-factor",
    name: "Electrical Cleanup Labor",
    code: "ELEC-CLEANUP",
    category: "Electrical Job Expense",
    description: "Apply where cleanup is carried as a labor factor from the electrical recapitulation form.",
    impact: "labor_hours",
    value: 1.01,
    appliesTo: "Electrical labor",
    scope: { mode: "category", analyticsBuckets: ["labour", "labor"] },
    confidence: "high",
    sourceType: "knowledge",
    sourceId: electricalBook.bookId,
    sourceRef: bookSourceRef({
      ...electricalBook,
      locator: "Recapitulation sheet",
      basis: "Manual recapitulation includes cleanup as 1% of labor.",
      formula: "+1% of labor",
    }),
    tags: ["electrical", "cleanup", "job-expense"],
  },
  ...LABOR_CONDITION_FACTOR_PRESETS,
  {
    id: "temperature-productivity",
    name: "Temperature Productivity",
    code: "TEMP-PROD",
    category: "Weather",
    description: "Parameterized temperature and humidity productivity factor using the researched temperature productivity sample grid.",
    impact: "labor_hours",
    value: 1,
    appliesTo: "Labor exposed to ambient conditions",
    applicationScope: "both",
    scope: { mode: "category", analyticsBuckets: ["labour", "labor"] },
    formulaType: "temperature_productivity",
    parameters: {
      temperature: 20,
      temperatureUnit: "C",
      humidity: 60,
      sampleData: NECA_TEMPERATURE_PRODUCTIVITY_SAMPLES,
    },
    confidence: "medium",
    sourceType: "condition_difficulty",
    sourceId: "temperature-productivity-tool",
    sourceRef: {
      title: "Temperature Productivity Tool",
      fileName: "../adminapp2-main/resources/views/quotes/tools/toolNECATemperature.blade.php",
      pluginSlug: "toolNECATemperature",
      locator: "sampleData / calculateTemperatureProductivity",
      basis: "Legacy tool selects the nearest temperature/humidity productivity sample, then applies lost productivity as additional labor hours.",
      formula: "lost productivity % = 100 - nearest sample productivity; multiplier = 1 + lost%/100",
      verification: "Lifted from the legacy adminapp2 temperature productivity tool.",
    },
    tags: ["weather", "temperature", "humidity", "productivity"],
  },
  {
    id: "extended-duration",
    name: "Extended Duration",
    code: "EXT-DURATION",
    category: "Schedule",
    description: "Parameterized extended-duration factor. Interpolates the researched labor-hour table, then scales additional hours by workers and months extended.",
    impact: "labor_hours",
    value: 1,
    appliesTo: "Electrical labor",
    applicationScope: "global",
    scope: { mode: "category", analyticsBuckets: ["labour", "labor"], categoryNames: ["Electrical", "Labour", "Labor"] },
    formulaType: "extended_duration",
    parameters: {
      monthsExtended: 0,
      workers: null,
      table: NECA_EXTENDED_DURATION_TABLE,
    },
    confidence: "medium",
    sourceType: "condition_difficulty",
    sourceId: "extended-duration-tool",
    sourceRef: {
      title: "Extended Duration Tool",
      fileName: "../adminapp2-main/resources/views/quotes/tools/toolNECAExtendedDuration.blade.php",
      pluginSlug: "toolNECAExtendedDuration",
      locator: "extendedDurationData / getSyntheticRow / recalcSynthetic",
      basis: "Legacy tool interpolates by base labor hours and computes additional hours from workers and months extended.",
      formula: "additional hours = (interpolated extraHours / interpolated workers) * selected workers * months extended",
      verification: "Lifted from the legacy adminapp2 extended-duration tool.",
    },
    tags: ["schedule", "duration", "extended-duration"],
  },
];

export function estimateFactorPresetToInput(preset: EstimateFactorPreset): Omit<EstimateFactor, "id" | "revisionId" | "order"> {
  return {
    name: preset.name,
    code: preset.code,
    description: preset.description,
    category: preset.category,
    impact: preset.impact,
    value: preset.value,
    active: true,
    appliesTo: preset.appliesTo,
    applicationScope: preset.applicationScope ?? "both",
    scope: preset.scope,
    formulaType: preset.formulaType ?? "fixed_multiplier",
    parameters: preset.parameters ?? {},
    confidence: preset.confidence,
    sourceType: preset.sourceType,
    sourceId: preset.sourceId ?? null,
    sourceRef: preset.sourceRef,
    tags: preset.tags,
  };
}
