import type { BidwrightStore } from "./models.js";

export const mockStore: BidwrightStore = {
  projects: [
    {
      id: "project-hospital-expansion",
      name: "City Hospital Mechanical Plant Expansion",
      clientName: "Metro Health Authority",
      location: "Toronto, ON",
      packageName: "City Hospital RFQ Package",
      packageUploadedAt: "2026-03-21T14:30:00.000Z",
      ingestionStatus: "review",
      summary:
        "Deep bid package with specs, RFQ, coordinated drawings, addenda, and a large estimating reference library. The current estimate is grounded in source citations and reviewed AI output.",
      createdAt: "2026-03-21T14:30:00.000Z",
      updatedAt: "2026-03-22T11:45:00.000Z",
    },
  ],
  sourceDocuments: [
    {
      id: "doc-rfq",
      projectId: "project-hospital-expansion",
      fileName: "RFQ_01.pdf",
      fileType: "pdf",
      documentType: "rfq",
      pageCount: 42,
      checksum: "sha256:rfq-01",
      storagePath: "projects/project-hospital-expansion/source/rfq_01.pdf",
      extractedText: "Request for Quotation covering mechanical plant expansion and shutdown work.",
      createdAt: "2026-03-21T14:31:00.000Z",
      updatedAt: "2026-03-21T14:32:00.000Z",
    },
    {
      id: "doc-specs",
      projectId: "project-hospital-expansion",
      fileName: "Project_Specifications.pdf",
      fileType: "pdf",
      documentType: "spec",
      pageCount: 318,
      checksum: "sha256:spec-01",
      storagePath: "projects/project-hospital-expansion/source/specs.pdf",
      extractedText:
        "Mechanical specification sections for piping, insulation, controls, test and balance, and commissioning.",
      createdAt: "2026-03-21T14:31:00.000Z",
      updatedAt: "2026-03-21T14:34:00.000Z",
    },
    {
      id: "doc-drawings",
      projectId: "project-hospital-expansion",
      fileName: "Issued_For_Bid_Drawings.zip",
      fileType: "zip",
      documentType: "drawing",
      pageCount: 76,
      checksum: "sha256:drawing-01",
      storagePath: "projects/project-hospital-expansion/source/drawings.zip",
      extractedText:
        "Sheet set includes mechanical plans, risers, details, and equipment schedules.",
      createdAt: "2026-03-21T14:31:00.000Z",
      updatedAt: "2026-03-21T14:35:00.000Z",
    },
  ],
  quotes: [
    {
      id: "quote-main",
      projectId: "project-hospital-expansion",
      quoteNumber: "BW-260321-001",
      title: "Hospital Mechanical Plant Expansion",
      status: "review",
      currentRevisionId: "rev-0",
      customerExistingNew: "Existing",
      customerId: null,
      customerString: "Metro Health Authority",
      customerContactId: null,
      customerContactString: "John Smith",
      customerContactEmailString: "jsmith@metrohealth.ca",
      departmentId: null,
      userId: null,
      createdAt: "2026-03-21T14:40:00.000Z",
      updatedAt: "2026-03-22T11:45:00.000Z",
    },
  ],
  revisions: [
    {
      id: "rev-0",
      quoteId: "quote-main",
      revisionNumber: 0,
      title: "Budgetary Takeoff",
      description:
        "Mechanical piping, equipment setting, insulation, and commissioning scope pulled from the uploaded customer package.",
      notes:
        "Review shutdown window, crane access, and phasing assumptions before release.",
      breakoutStyle: "phase_detail",
      phaseWorksheetEnabled: true,
      useCalculatedTotal: true,
      type: "Budget",
      scratchpad: "",
      leadLetter: "",
      dateEstimatedShip: null,
      dateQuote: "2026-03-21",
      dateDue: "2026-04-15",
      dateWalkdown: null,
      dateWorkStart: "2026-05-01",
      dateWorkEnd: "2026-09-30",
      shippingMethod: "",
      shippingTerms: "",
      freightOnBoard: "",
      status: "Open",
      defaultMarkup: 0.2,
      necaDifficulty: "Normal",
      followUpNote: "",
      printEmptyNotesColumn: false,
      printCategory: [],
      printPhaseTotalOnly: false,
      showOvertimeDoubletime: false,
      grandTotal: 1239854,
      regHours: 2584,
      overHours: 0,
      doubleHours: 0,
      breakoutPackage: [],
      calculatedCategoryTotals: [],
      subtotal: 1239854,
      cost: 969040,
      estimatedProfit: 270814,
      estimatedMargin: 0.2184,
      totalHours: 2584,
      createdAt: "2026-03-21T14:42:00.000Z",
      updatedAt: "2026-03-22T11:44:00.000Z",
    },
  ],
  worksheets: [
    { id: "ws-general", revisionId: "rev-0", name: "General Conditions", order: 1 },
    { id: "ws-piping", revisionId: "rev-0", name: "Piping", order: 2 },
    { id: "ws-equipment", revisionId: "rev-0", name: "Equipment", order: 3 },
  ],
  worksheetItems: [
    {
      id: "li-1",
      worksheetId: "ws-piping",
      phaseId: "phase-2",
      category: "Labour",
      entityType: "LaborClass",
      entityName: "Journeyman Pipefitter",
      description: "Install chilled water piping and supports",
      quantity: 1480,
      uom: "HR",
      cost: 119040,
      markup: 0.55,
      price: 190464,
      laborHourReg: 1480,
      laborHourOver: 0,
      laborHourDouble: 0,
      lineOrder: 1,
    },
    {
      id: "li-2",
      worksheetId: "ws-piping",
      phaseId: "phase-2",
      category: "Materials",
      entityType: "Material",
      entityName: "Pipe and Fittings",
      description: "8-inch and 10-inch steel pipe, fittings, hangers, and accessories",
      quantity: 1,
      uom: "LS",
      cost: 356500,
      markup: 0.24,
      price: 445625,
      laborHourReg: 0,
      laborHourOver: 0,
      laborHourDouble: 0,
      lineOrder: 2,
    },
    {
      id: "li-3",
      worksheetId: "ws-equipment",
      phaseId: "phase-2",
      category: "Equipment",
      entityType: "EquipmentRate",
      entityName: "75 Ton Crane",
      description: "Mobilization, pick, and reset support",
      quantity: 4,
      uom: "DAY",
      cost: 18500,
      markup: 0.25,
      price: 23125,
      laborHourReg: 4,
      laborHourOver: 0,
      laborHourDouble: 0,
      lineOrder: 1,
    },
    {
      id: "li-4",
      worksheetId: "ws-general",
      phaseId: "phase-1",
      category: "Subcontractors",
      entityType: "Subcontractor",
      entityName: "Test and Balance",
      description: "TAB contractor for final system balancing and verification",
      quantity: 1,
      uom: "LS",
      cost: 62000,
      markup: 0.18,
      price: 73160,
      laborHourReg: 0,
      laborHourOver: 0,
      laborHourDouble: 0,
      lineOrder: 1,
    },
    {
      id: "li-5",
      worksheetId: "ws-piping",
      phaseId: "phase-2",
      category: "Materials",
      entityType: "Material",
      entityName: "Insulation Package",
      description: "Pipe insulation, jacketing, and accessories for exposed runs",
      quantity: 1,
      uom: "LS",
      cost: 121000,
      markup: 0.23,
      price: 148830,
      laborHourReg: 0,
      laborHourOver: 0,
      laborHourDouble: 0,
      lineOrder: 3,
    },
    {
      id: "li-6",
      worksheetId: "ws-general",
      phaseId: "phase-2",
      category: "Subcontractors",
      entityType: "Subcontractor",
      entityName: "Controls Integration",
      description: "BMS integration, controls programming, and point-to-point testing",
      quantity: 1,
      uom: "LS",
      cost: 182000,
      markup: 0.2,
      price: 218400,
      laborHourReg: 0,
      laborHourOver: 0,
      laborHourDouble: 0,
      lineOrder: 2,
    },
    {
      id: "li-7",
      worksheetId: "ws-general",
      phaseId: "phase-2",
      category: "Labour",
      entityType: "LaborClass",
      entityName: "Commissioning Crew",
      description: "Commissioning support, turnover, and closeout assistance",
      quantity: 1100,
      uom: "HR",
      cost: 110000,
      markup: 0.275,
      price: 140250,
      laborHourReg: 1100,
      laborHourOver: 0,
      laborHourDouble: 0,
      lineOrder: 3,
    },
  ],
  phases: [
    {
      id: "phase-1",
      revisionId: "rev-0",
      number: "01",
      name: "Preconstruction and Mobilization",
      description: "Submittals, coordination, permits, and site setup.",
      order: 1,
    },
    {
      id: "phase-2",
      revisionId: "rev-0",
      number: "02",
      name: "Mechanical Rough-In",
      description: "Main piping, equipment setting, and insulation rough-in.",
      order: 2,
    },
  ],
  modifiers: [
    {
      id: "mod-1",
      revisionId: "rev-0",
      name: "Contingency",
      type: "Surcharge",
      appliesTo: "All",
      percentage: 0.05,
      amount: null,
      show: "Yes",
    },
    {
      id: "mod-2",
      revisionId: "rev-0",
      name: "Fuel Surcharge",
      type: "Surcharge",
      appliesTo: "Labour",
      percentage: 0.03,
      amount: null,
      show: "No",
    },
  ],
  additionalLineItems: [
    {
      id: "ali-1",
      revisionId: "rev-0",
      name: "Bid Bond Allowance",
      description: "Allow for bond premium associated with submission requirements.",
      type: "LineItemAdditional",
      amount: 18500,
    },
  ],
  conditions: [
    {
      id: "cond-1",
      revisionId: "rev-0",
      type: "Inclusion",
      value: "Includes standard working hours and one mobilization.",
      order: 1,
    },
    {
      id: "cond-2",
      revisionId: "rev-0",
      type: "Exclusion",
      value: "Excludes asbestos abatement, major structural steel, and night shift premiums.",
      order: 2,
    },
  ],
  catalogs: [
    {
      id: "catalog-labor",
      name: "Mechanical Labor Book",
      kind: "labor",
      scope: "global",
      projectId: null,
      description: "Standalone labor class catalog with rates and burdens.",
    },
    {
      id: "catalog-equipment",
      name: "Rental Equipment Rates",
      kind: "equipment",
      scope: "global",
      projectId: null,
      description: "Equipment rate book for cranes, lifts, and specialty rental.",
    },
    {
      id: "catalog-library",
      name: "Mechanical Pipefitting Library",
      kind: "knowledge_library",
      scope: "global",
      projectId: null,
      description: "Long-form reference knowledge for estimating and production planning.",
    },
  ],
  catalogItems: [
    {
      id: "catalog-item-l1",
      catalogId: "catalog-labor",
      code: "LAB-PF-01",
      name: "Journeyman Pipefitter",
      unit: "HR",
      unitCost: 62,
      unitPrice: 95,
      metadata: { burdenIncluded: false, trade: "Mechanical" },
    },
    {
      id: "catalog-item-e1",
      catalogId: "catalog-equipment",
      code: "EQ-CRANE-75",
      name: "75 Ton Crane",
      unit: "DAY",
      unitCost: 16800,
      unitPrice: 21000,
      metadata: { operatorIncluded: false },
    },
    {
      id: "catalog-item-k1",
      catalogId: "catalog-library",
      code: "BOOK-PIPE-2025",
      name: "Mechanical Pipefitting Handbook",
      unit: "PAGE",
      unitCost: 0,
      unitPrice: 0,
      metadata: { pages: 392, sourceType: "reference_book" },
    },
  ],
  aiRuns: [
    {
      id: "airun-1",
      projectId: "project-hospital-expansion",
      revisionId: "rev-0",
      kind: "scope",
      status: "complete",
      model: "gpt-5.4-mini",
      promptVersion: "scope-v1",
      input: {
        sources: ["doc-rfq", "doc-specs", "doc-drawings"],
        question: "Break the package into phases and estimate scope risk.",
      },
      output: {
        phases: ["Preconstruction and Mobilization", "Mechanical Rough-In"],
        riskFlags: ["shutdown window", "crane access", "night work not priced"],
      },
      createdAt: "2026-03-22T10:15:00.000Z",
      updatedAt: "2026-03-22T10:17:00.000Z",
    },
  ],
  citations: [
    {
      id: "cite-1",
      projectId: "project-hospital-expansion",
      aiRunId: "airun-1",
      sourceDocumentId: "doc-specs",
      resourceType: "source_document",
      resourceKey: "Project_Specifications.pdf#p112",
      pageStart: 112,
      pageEnd: 114,
      excerpt: "Mechanical contractor shall coordinate shutdowns with facility operations.",
      confidence: 0.92,
    },
    {
      id: "cite-2",
      projectId: "project-hospital-expansion",
      aiRunId: "airun-1",
      sourceDocumentId: "doc-drawings",
      resourceType: "source_document",
      resourceKey: "Issued_For_Bid_Drawings.zip#sheet-m301",
      pageStart: 31,
      pageEnd: 31,
      excerpt: "Mechanical room layout shows major equipment replacement and rerouting.",
      confidence: 0.88,
    },
  ],
  labourRates: [],
  activities: [],
  conditionLibrary: [],
  reportSections: [],
  jobs: [],
};
