import { readFile, unlink } from "node:fs/promises";
import { join } from "node:path";

const GENERATED_CONFIG_PATHS = [
  ".bidwright-mcp-config.json",
  "opencode.json",
  join(".claude", "settings.json"),
  join(".gemini", "settings.json"),
] as const;

const LEGACY_CODEX_CREDENTIAL_PATHS = [
  join(".codex", "auth.json"),
  join(".codex", "cap_sid"),
] as const;

function containsPlaintextBidwrightRuntimeToken(content: string): boolean {
  if (!/"BIDWRIGHT_AUTH_TOKEN"\s*:/.test(content)) return false;
  return !(
    content.includes("${BIDWRIGHT_AUTH_TOKEN}") ||
    content.includes("{env:BIDWRIGHT_AUTH_TOKEN}")
  );
}

/**
 * Remove credentials/config generated by pre-hardening Bidwright releases.
 * This runs after every workspace restore, independent of which adapter will
 * execute next, so stale secrets cannot be re-snapshotted by another runtime.
 */
export async function removeLegacyRuntimeCredentials(projectDir: string): Promise<void> {
  await Promise.all(
    LEGACY_CODEX_CREDENTIAL_PATHS.map((relativePath) =>
      unlink(join(projectDir, relativePath)).catch(() => {}),
    ),
  );

  await Promise.all(
    GENERATED_CONFIG_PATHS.map(async (relativePath) => {
      const path = join(projectDir, relativePath);
      const content = await readFile(path, "utf8").catch(() => "");
      if (containsPlaintextBidwrightRuntimeToken(content)) {
        await unlink(path).catch(() => {});
      }
    }),
  );

  const codexConfigPath = join(projectDir, ".codex", "config.toml");
  const codexConfig = await readFile(codexConfigPath, "utf8").catch(() => "");
  if (
    codexConfig.includes("[mcp_servers.bidwright]") &&
    codexConfig.includes("BIDWRIGHT_AUTH_TOKEN")
  ) {
    await unlink(codexConfigPath).catch(() => {});
  }
}
